# Generated by Django 3.2.16 on 2022-12-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Add_product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='category',
            new_name='Category',
        ),
    ]
